services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - "8081:80"
    volumes:
      - ./services/vaultwarden/data:/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./services/grafana/data:/var/lib/grafana
    restart: unless-stopped
