- Platform:
    - Home:
        href: http://homepage.localhost:9090
        description: Platform dashboard

    - Vaultwarden:
        href: http://vaultwarden.localhost:9090
        description: Password manager
        
    - Gitea:
        href: http://gitea.localhost:9090
        description: Git hosting

    - Grafana:
        href: http://grafana.localhost:9090
        description: Metrics dashboard
     
