services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      - HOME_HOST=${HOME_HOST}
      - VAULT_HOST=${VAULT_HOST}
      - GITEA_HOST=${GITEA_HOST}
      - GRAFANA_HOST=${GRAFANA_HOST}
    ports: 
      - "${PORT:-8080}:80"
      - "443:443"
    volumes:
      - ../proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - HOMEPAGE_ALLOWED_HOSTS=${HOME_HOST}
    volumes:
      - ../homepage:/app/config
    restart: unless-stopped
    networks:
      - homelab

  vaultwarden:
    image: vaultwarden/server:latest
    profiles:
      - vaultwarden
    restart: unless-stopped
    volumes:
      - ../data/vaultwarden:/data
    networks:
      homelab:
        aliases:
          - vaultwarden


  gitea:
    image: gitea/gitea:latest
    restart: unless-stopped
    profiles:
      - gitea
    volumes:
      - ../data/gitea:/data
    networks:
      homelab:
        aliases:
          - gitea

  grafana:
    image: grafana/grafana:latest
    profiles:
      - grafana
    restart: unless-stopped
    volumes:
      - ../data/grafana:/var/lib/grafana
    networks:
      homelab:
        aliases:
          - grafana

networks:
  homelab:

volumes:
  caddy_data:
  caddy_config:
