version: "3.9"

services:
  caddy:
    image: caddy:2
    container_name: homelab-caddy
    restart: unless stopped
    ports: 
      - "8080:80"
    volumes:
      - ..proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    volumes:
      caddy_data:
      caddy_config:

