name: Installer Test

on: [push]

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: 
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo ./scripts/setup.sh --non-interactive

  debian:
    runs-on: ubuntu-latest
    container: debian:12
    steps:
      - uses: 
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          apt-get update
          apt-get install -y git ca-certificates
          ./scripts/setup.sh --non-interactive
     
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: 
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Sy --noconfirm git
          ./scripts/setup.sh --non-interactive
